# Compile win32 startup.exe
#
name: win32

on:  
  push :
    paths:
      - 'win_startup/**'
    branches: [ main ]

jobs:
  build:
    runs-on: windows-lastest
    
    steps:
      - uses: actions/checkout@v1

      - name: Install vc env
        uses: jurplel/install-qt-action@v2.13.0
        with:
          version: 5.9.9
          arch: win32_msvc2015
          cached: 'false'

      - name: build-msvc
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" "x86"
          nmake clean
          nmake 
          mkdir -p output/release
          cp report_service.exe output/release

      - name: package
        uses: actions/upload-artifact@v2
        with:
          name: startup
          path: output/release

      - name: downloader
        uses: actions/download-artifact@v2
        with: 
          name: startup
